### ISSUE TITLE
current version crahes in heroku

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/frontend-dash#1]
```
2017-11-01T15:07:36.729843+00:00 heroku[router]: at=info method=POST path="/_dash-update-component" host=macrodash.herokuapp.com request_id=796fd55c-29b8-4178-acf1-ce3f90e1010e fwd="91.220.93.136" dyno=web.1 connect=0ms service=3ms status=200 bytes=419 protocol=https

2017-11-01T15:07:36.918710+00:00 heroku[router]: at=info method=POST path="/_dash-update-component" host=macrodash.herokuapp.com request_id=1277318b-79b8-490e-bb8f-45d4771191d9 fwd="91.220.93.136" dyno=web.1 connect=0ms service=191ms status=500 bytes=456 protocol=https

2017-11-01T15:07:36.914720+00:00 app[web.1]: [2017-11-01 15:07:36,914] ERROR in app: Exception on /_dash-update-component [POST]

2017-11-01T15:07:36.914737+00:00 app[web.1]: Traceback (most recent call last):

2017-11-01T15:07:36.914740+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app

2017-11-01T15:07:36.914741+00:00 app[web.1]:     response = self.full_dispatch_request()

2017-11-01T15:07:36.914742+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request

2017-11-01T15:07:36.914742+00:00 app[web.1]:     rv = self.handle_user_exception(e)

2017-11-01T15:07:36.914743+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception

2017-11-01T15:07:36.914744+00:00 app[web.1]:     reraise(exc_type, exc_value, tb)

2017-11-01T15:07:36.914744+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise

2017-11-01T15:07:36.914745+00:00 app[web.1]:     raise value

2017-11-01T15:07:36.914746+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request

2017-11-01T15:07:36.914747+00:00 app[web.1]:     rv = self.dispatch_request()

2017-11-01T15:07:36.914747+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request

2017-11-01T15:07:36.914748+00:00 app[web.1]:     return self.view_functions[rule.endpoint](**req.view_args)

2017-11-01T15:07:36.914749+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/dash/dash.py", line 541, in dispatch

2017-11-01T15:07:36.914750+00:00 app[web.1]:     return self.callback_map[target_id]['callback'](*args)

2017-11-01T15:07:36.914750+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/dash/dash.py", line 498, in add_context

2017-11-01T15:07:36.914751+00:00 app[web.1]:     output_value = func(*args, **kwargs)

2017-11-01T15:07:36.914751+00:00 app[web.1]:   File "/app/app.py", line 132, in update_graph_parameters

2017-11-01T15:07:36.914752+00:00 app[web.1]:     data_list = [get_time_series_dict(freq, name1)]

2017-11-01T15:07:36.914753+00:00 app[web.1]:   File "/app/app.py", line 81, in get_time_series_dict

2017-11-01T15:07:36.914753+00:00 app[web.1]:     data = get_from_api_datapoints(freq, name)

2017-11-01T15:07:36.914754+00:00 app[web.1]:   File "/app/app.py", line 74, in get_from_api_datapoints

2017-11-01T15:07:36.914754+00:00 app[web.1]:     data = requests.get(url).json()

2017-11-01T15:07:36.914755+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/requests/models.py", line 892, in json

2017-11-01T15:07:36.914756+00:00 app[web.1]:     return complexjson.loads(self.text, **kwargs)

2017-11-01T15:07:36.914757+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/json/__init__.py", line 354, in loads

2017-11-01T15:07:36.914758+00:00 app[web.1]:     return _default_decoder.decode(s)

2017-11-01T15:07:36.914758+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/json/decoder.py", line 339, in decode

2017-11-01T15:07:36.914759+00:00 app[web.1]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())

2017-11-01T15:07:36.914760+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/json/decoder.py", line 357, in raw_decode

2017-11-01T15:07:36.914760+00:00 app[web.1]:     raise JSONDecodeError("Expecting value", s, err.value) from None

2017-11-01T15:07:36.914765+00:00 app[web.1]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Perevedko** [comment]
fixed @ https://github.com/mini-kep/frontend-dash/commit/cf872230f83280d8e5acdeab4f84f869bb6b889d

**Comment by epogrebnyak** [comment]
@Perevedko, many thanks!
